/**
 * QMS Enterprise Mock Seed Data
 * Rich initial data ensuring comprehensive workflow, library, DAR, and task coverage.
 */

export const defaultSeedCurrentUser = {
  id: 'EMP-001',
  empId: 'EMP-001',
  name: 'ธนาวุฒิ สมควรกิจดำรง',
  fullName: 'ธนาวุฒิ สมควรกิจดำรง',
  email: 'thanawut.s@company.com',
  position: 'Technology Project Leader / DCC Supervisor',
  department: 'DC',
  dept: 'DC',
  primary_department: 'DC',
  depts: ['DC'],
  affiliated_departments: ['DC', 'QC', 'MGMT'],
  affiliatedDepartments: ['DC', 'QC', 'MGMT'],
  role: 'DCC_ADMIN',
  isDcc: true,
  isDccAdmin: true,
  level: 4,
  approval_level: 4,
  status: 'Active',
  permissions: ['DAR_CREATE', 'TASK_ACCESS', 'VIEW_REGISTER', 'DCC_ADMIN'],
  canCreateDar: true,
  canAccessTasks: true,
  canViewRegister: true,
  isWorkflowUser: true
};

export const defaultSeedDocuments = [
  // 1. WI-QC-01 Rev.01 (EFFECTIVE)
  {
    id: 'WI-QC-01_REV_01',
    code: 'WI-QC-01',
    docNo: 'WI-QC-01',
    document_code: 'WI-QC-01',
    doc_code: 'WI-QC-01',
    title: 'WI-QC-01',
    name: 'ขั้นตอนการตรวจสอบคุณภาพวัตถุดิบรับเข้า',
    document_title: 'ขั้นตอนการตรวจสอบคุณภาพวัตถุดิบรับเข้า',
    docName: 'ขั้นตอนการตรวจสอบคุณภาพวัตถุดิบรับเข้า',
    docTitle: 'WI-QC-01',
    status: 'EFFECTIVE',
    is_superseded: false,
    is_active: true,
    department: 'QC',
    dept: 'QC',
    ownerId: 'U005',
    ownerName: 'บีม',
    rev: '01',
    revision: '01',
    doc_version: '01',
    effectiveDate: '2025-06-20',
    effective_date: '2025-06-20',
    darId: 'DAR-2026-002',
    darNo: 'DAR-2026-002',
    access_control: {
      scope: 'GENERAL',
      authorized_depts: [],
      authorized_users: [],
      min_access_level: 1
    },
    distributions: [
      { copy_number: '01', copy_no: '01', department: 'QC', location: 'QC Office', station_name: 'QC Office' }
    ],
    related_standards: ['ISO 9001:2015', 'GHPs'],
    relatedStandards: ['ISO 9001:2015', 'GHPs']
  },

  // 2. WI-QC-01 Rev.00 (SUPERSEDED)
  {
    id: 'WI-QC-01_REV_00',
    code: 'WI-QC-01',
    docNo: 'WI-QC-01',
    document_code: 'WI-QC-01',
    doc_code: 'WI-QC-01',
    title: 'WI-QC-01',
    name: 'ขั้นตอนการตรวจสอบคุณภาพวัตถุดิบรับเข้า',
    document_title: 'ขั้นตอนการตรวจสอบคุณภาพวัตถุดิบรับเข้า',
    docName: 'ขั้นตอนการตรวจสอบคุณภาพวัตถุดิบรับเข้า',
    docTitle: 'WI-QC-01',
    status: 'SUPERSEDED',
    is_superseded: true,
    is_active: false,
    department: 'QC',
    dept: 'QC',
    ownerId: 'U005',
    ownerName: 'บีม',
    rev: '00',
    revision: '00',
    doc_version: '00',
    effectiveDate: '2025-01-15',
    effective_date: '2025-01-15',
    superseded_at: '2025-06-20T09:00:00.000Z',
    supersededAt: '2025-06-20T09:00:00.000Z',
    supersededByRev: '01',
    darId: 'DAR-2026-001',
    darNo: 'DAR-2026-001',
    access_control: {
      scope: 'GENERAL',
      authorized_depts: [],
      authorized_users: [],
      min_access_level: 1
    }
  },

  // 3. SOP-QC-01 Rev.01 (EFFECTIVE)
  {
    id: 'DOC-QC-SOP-01-R01',
    code: 'SOP-QC-01',
    docNo: 'SOP-QC-01',
    document_code: 'SOP-QC-01',
    doc_code: 'SOP-QC-01',
    title: 'SOP-QC-01',
    name: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    document_title: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    docName: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    docTitle: 'SOP-QC-01',
    status: 'EFFECTIVE',
    is_superseded: false,
    is_active: true,
    department: 'QC',
    dept: 'QC',
    ownerId: 'U005',
    ownerName: 'บีม',
    rev: '01',
    revision: '01',
    doc_version: '01',
    effectiveDate: '2026-02-01',
    effective_date: '2026-02-01',
    darId: 'DAR-2026-002',
    darNo: 'DAR-2026-002',
    access_control: {
      scope: 'GENERAL',
      authorized_depts: [],
      authorized_users: [],
      min_access_level: 1
    },
    distributions: [
      { copy_number: '01', copy_no: '01', department: 'QC', location: 'QC Office', station_name: 'QC Office' }
    ],
    related_standards: ['ISO 9001:2015', 'HACCP'],
    relatedStandards: ['ISO 9001:2015', 'HACCP']
  },

  // 4. SOP-QC-01 Rev.00 (SUPERSEDED)
  {
    id: 'DOC-QC-SOP-01-R00',
    code: 'SOP-QC-01',
    docNo: 'SOP-QC-01',
    document_code: 'SOP-QC-01',
    doc_code: 'SOP-QC-01',
    title: 'SOP-QC-01',
    name: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    document_title: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    docName: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    docTitle: 'SOP-QC-01',
    status: 'SUPERSEDED',
    is_superseded: true,
    is_active: false,
    department: 'QC',
    dept: 'QC',
    ownerId: 'U005',
    ownerName: 'บีม',
    rev: '00',
    revision: '00',
    doc_version: '00',
    effectiveDate: '2025-01-15',
    effective_date: '2025-01-15',
    superseded_at: '2026-02-01T09:00:00.000Z',
    supersededAt: '2026-02-01T09:00:00.000Z',
    supersededByRev: '01',
    darId: 'DAR-2026-001',
    darNo: 'DAR-2026-001',
    access_control: {
      scope: 'GENERAL',
      authorized_depts: [],
      authorized_users: [],
      min_access_level: 1
    }
  },

  // 5. SOP-PD-001 Rev.01 (EFFECTIVE, Baseline)
  {
    id: 'DOC-MOCK-1',
    title: 'SOP-PD-001',
    code: 'SOP-PD-001',
    docNo: 'SOP-PD-001',
    document_code: 'SOP-PD-001',
    doc_code: 'SOP-PD-001',
    name: 'มาตรฐานการควบคุมเครื่องตรวจจับโลหะ (Metal Detector)',
    document_title: 'มาตรฐานการควบคุมเครื่องตรวจจับโลหะ (Metal Detector)',
    docName: 'มาตรฐานการควบคุมเครื่องตรวจจับโลหะ (Metal Detector)',
    status: 'EFFECTIVE',
    department: 'PD',
    dept: 'PD',
    ownerId: 'U003',
    effectiveDate: '2025-07-16',
    rev: '01',
    revision: '01',
    doc_version: '01',
    access_control: {
      scope: 'GENERAL',
      authorized_depts: [],
      authorized_users: [],
      min_access_level: 1
    },
    distributions: [
      { copy_number: '01', copy_no: '01', department: 'PD', location: 'PD Office' }
    ]
  },

  // 6. WI-PD-015 Rev.01 (EFFECTIVE)
  {
    id: 'DOC-MOCK-2',
    title: 'WI-PD-015',
    code: 'WI-PD-015',
    docNo: 'WI-PD-015',
    document_code: 'WI-PD-015',
    doc_code: 'WI-PD-015',
    name: 'ขั้นตอนการล้างทำความสะอาดข้าวเหนียว',
    status: 'EFFECTIVE',
    department: 'PD',
    dept: 'PD',
    ownerId: 'U003',
    effectiveDate: '2025-05-25',
    rev: '01',
    revision: '01',
    doc_version: '01',
    access_control: {
      scope: 'DEPT_ONLY',
      authorized_depts: ['PD'],
      authorized_users: [],
      min_access_level: 1
    }
  }
];

export const defaultSeedDars = [
  // 1. DAR-2026-001 (NEW WI-QC-01, COMPLETED)
  {
    id: 'DAR-2026-001',
    darNo: 'DAR-2026-001',
    dar_no: 'DAR-2026-001',
    darNumber: 'DAR-2026-001',
    docId: 'WI-QC-01_REV_00',
    doc_id: 'WI-QC-01_REV_00',
    title: 'WI-QC-01',
    document_code: 'WI-QC-01',
    doc_code: 'WI-QC-01',
    docNo: 'WI-QC-01',
    docTitle: 'WI-QC-01',
    document_title: 'ขั้นตอนการตรวจสอบคุณภาพวัตถุดิบรับเข้า',
    docName: 'ขั้นตอนการตรวจสอบคุณภาพวัตถุดิบรับเข้า',
    name: 'ขั้นตอนการตรวจสอบคุณภาพวัตถุดิบรับเข้า',
    type: 'NEW_DOCUMENT',
    requestType: 'NEW_DOCUMENT',
    darType: 'NEW_DOCUMENT',
    docType: 'WI',
    doc_type: 'WI',
    revision: '00',
    target_revision: '00',
    targetRevision: '00',
    currentRevision: '00',
    previous_revision: '-',
    rev: '00',
    assignee_department: 'DC',
    department: 'QC',
    dept: 'QC',
    requester_department: 'QC',
    requesterDepartment: 'QC',
    status: 'COMPLETED',
    reason: 'จัดทำคู่มือปฏิบัติงานการตรวจสอบคุณภาพวัตถุดิบรับเข้าฉบับแรก (Genesis Rev.00)',
    effectiveDate: '2025-01-15',
    effective_date: '2025-01-15',
    requesterId: 'U005',
    requesterName: 'บีม',
    reviewerId: 'U003',
    reviewerName: 'กัลยาณี พลไกร',
    approverId: 'U004',
    approverName: 'คุณเรย์',
    submitted_date: '2025-01-05T08:00:00.000Z',
    date: '2025-01-05T08:00:00.000Z',
    created_at: '2025-01-05T08:00:00.000Z',
    completed_at: '2025-01-15T09:00:00.000Z'
  },

  // 2. DAR-2026-002 (REVISION SOP-QC-01, COMPLETED)
  {
    id: 'DAR-2026-002',
    darNo: 'DAR-2026-002',
    dar_no: 'DAR-2026-002',
    darNumber: 'DAR-2026-002',
    docId: 'DOC-QC-SOP-01-R01',
    doc_id: 'DOC-QC-SOP-01-R01',
    title: 'SOP-QC-01',
    document_code: 'SOP-QC-01',
    doc_code: 'SOP-QC-01',
    docNo: 'SOP-QC-01',
    docTitle: 'SOP-QC-01',
    document_title: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    docName: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    name: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    type: 'REVISION',
    requestType: 'REVISION',
    darType: 'REVISION',
    docType: 'SOP',
    doc_type: 'SOP',
    revision: '01',
    target_revision: '01',
    targetRevision: '01',
    currentRevision: '00',
    previous_revision: '00',
    rev: '01',
    department: 'QC',
    dept: 'QC',
    requester_department: 'QC',
    requesterDepartment: 'QC',
    status: 'COMPLETED',
    reason: 'ปรับปรุงเกณฑ์การชักตัวอย่างและการตรวจปล่อยวัตถุดิบ Rev.01',
    effectiveDate: '2026-02-01',
    effective_date: '2026-02-01',
    requesterId: 'U005',
    requesterName: 'บีม',
    reviewerId: 'U003',
    reviewerName: 'กัลยาณี พลไกร',
    approverId: 'U004',
    approverName: 'คุณเรย์',
    submitted_date: '2026-01-15T08:00:00.000Z',
    date: '2026-01-15T08:00:00.000Z',
    created_at: '2026-01-15T08:00:00.000Z',
    completed_at: '2026-02-01T09:00:00.000Z'
  },

  // 3. DAR-2026-003 (OBSOLETE SOP-QC-01, PENDING_REVIEW / รอการทบทวน)
  {
    id: 'DAR-2026-003',
    darNo: 'DAR-2026-003',
    dar_no: 'DAR-2026-003',
    darNumber: 'DAR-2026-003',
    docId: 'DOC-QC-SOP-01-R01',
    doc_id: 'DOC-QC-SOP-01-R01',
    title: 'SOP-QC-01',
    document_code: 'SOP-QC-01',
    doc_code: 'SOP-QC-01',
    docNo: 'SOP-QC-01',
    docTitle: 'SOP-QC-01',
    document_title: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    docName: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    name: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    type: 'OBSOLETE',
    requestType: 'OBSOLETE',
    darType: 'OBSOLETE',
    docType: 'SOP',
    doc_type: 'SOP',
    revision: '01',
    target_revision: '01',
    targetRevision: '01',
    currentRevision: '01',
    previous_revision: '01',
    rev: '01',
    department: 'QC',
    dept: 'QC',
    requester_department: 'QC',
    requesterDepartment: 'QC',
    status: 'PENDING_REVIEW',
    reason: 'ขอยกเลิกเอกสารเนื่องจากปรับปรุงเข้าสู่ระบบดิจิทัลและการทำงานแบบไร้กระดาษ',
    effectiveDate: '2026-03-01',
    effective_date: '2026-03-01',
    requesterId: 'U005',
    requesterName: 'บีม',
    reviewerId: 'U003',
    reviewerName: 'กัลยาณี พลไกร',
    approverId: 'U004',
    approverName: 'คุณเรย์',
    submitted_date: '2026-02-15T08:00:00.000Z',
    date: '2026-02-15T08:00:00.000Z',
    created_at: '2026-02-15T08:00:00.000Z'
  }
];

export const defaultSeedTasks = [
  // 1. Task แจกจ่ายสำเนา SOP-QC-01 Rev.01 (Assignee: DC)
  {
    id: 'task-dist-sop-qc-01-rev01',
    type: 'DISTRIBUTE_HARDCOPY',
    taskType: 'DISTRIBUTE',
    task_type: 'DISTRIBUTE',
    category: 'DISTRIBUTION',
    title: 'แจกจ่ายสำเนาควบคุมฉบับพิมพ์: SOP-QC-01 Rev.01',
    description: 'ดำเนินการจัดพิมพ์ ประทับตรา และแจกจ่ายสำเนาควบคุม SOP-QC-01 Rev.01 ไปยังจุดใช้งาน QC Office',
    docCode: 'SOP-QC-01',
    doc_code: 'SOP-QC-01',
    docTitle: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    docName: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    target_revision: '01',
    targetRevision: '01',
    revision: '01',
    rev: '01',
    doc_version: '01',
    department: 'DC',
    target_department: 'DC',
    targetDepartment: 'DC',
    targetRole: 'DCC_ADMIN',
    target_role: 'DCC_ADMIN',
    assignedToRole: 'DCC_ADMIN',
    owner_dept: 'QC',
    currentHandlerDepartment: 'DC',
    assignedToDept: 'DC',
    assigneeId: 'EMP-001',
    assignee_id: 'EMP-001',
    assigneeName: 'ธนาวุฒิ สมควรกิจดำรง',
    status: 'PENDING',
    darId: 'DAR-2026-002',
    location: 'QC Office',
    locationName: 'QC Office',
    copy_no: '01',
    destinationDept: 'QC',
    createdAt: '2026-02-01T08:00:00.000Z',
    dueDate: '2026-02-10T17:00:00.000Z',
    priority: 'HIGH'
  },

  // 2. Task เรียกคืนสำเนา SOP-QC-01 Rev.00 (Assignee: DC)
  {
    id: 'task-recall-sop-qc-01-rev00',
    type: 'RECALL_HARDCOPY',
    taskType: 'RECALL',
    task_type: 'RECALL',
    category: 'RECALL',
    title: 'เรียกคืนสำเนาควบคุมฉบับเดิม: SOP-QC-01 Rev.00',
    description: 'ดำเนินการเรียกคืนสำเนาควบคุมฉบับเดิมที่ถูกแทนที่ SOP-QC-01 Rev.00 จากจุดใช้งาน QC Office เพื่อทำลาย',
    docCode: 'SOP-QC-01',
    doc_code: 'SOP-QC-01',
    docTitle: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    docName: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    target_revision: '00',
    targetRevision: '00',
    currentRevision: '00',
    current_revision: '00',
    revision: '00',
    rev: '00',
    doc_version: '00',
    department: 'DC',
    target_department: 'DC',
    targetDepartment: 'DC',
    targetRole: 'DCC_ADMIN',
    target_role: 'DCC_ADMIN',
    assignedToRole: 'DCC_ADMIN',
    owner_dept: 'QC',
    currentHandlerDepartment: 'DC',
    assignedToDept: 'DC',
    assigneeId: 'EMP-001',
    assignee_id: 'EMP-001',
    assigneeName: 'ธนาวุฒิ สมควรกิจดำรง',
    status: 'PENDING',
    darId: 'DAR-2026-002',
    location: 'QC Office',
    locationName: 'QC Office',
    copy_no: '01',
    destinationDept: 'QC',
    createdAt: '2026-02-01T08:00:00.000Z',
    dueDate: '2026-02-10T17:00:00.000Z',
    priority: 'HIGH'
  },

  // 3. Task ทบทวนคำร้องขอยกเลิกเอกสาร SOP-QC-01: DAR-2026-003 (Assignee: กัลยาณี พลไกร / QC)
  {
    id: 'task-review-dar-2026-003',
    type: 'REVIEW',
    taskType: 'REVIEW',
    task_type: 'REVIEW',
    category: 'DAR_APPROVAL',
    title: 'ทบทวนคำร้องขอยกเลิกเอกสาร: SOP-QC-01 (DAR-2026-003)',
    description: 'กรุณาทบทวนคำร้องขอยกเลิกเอกสาร SOP-QC-01 ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    darId: 'DAR-2026-003',
    dar_id: 'DAR-2026-003',
    docId: 'DOC-QC-SOP-01-R01',
    doc_id: 'DOC-QC-SOP-01-R01',
    docCode: 'SOP-QC-01',
    doc_code: 'SOP-QC-01',
    docTitle: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    docName: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    target_revision: '01',
    targetRevision: '01',
    revision: '01',
    rev: '01',
    doc_version: '01',
    department: 'QC',
    departmentName: 'ฝ่ายประกันและควบคุมคุณภาพ',
    target_department: 'QC',
    owner_dept: 'QC',
    currentHandlerDepartment: 'QC',
    assignedToDept: 'QC',
    assigneeId: 'U003',
    assignee_id: 'U003',
    assigneeName: 'กัลยาณี พลไกร',
    requesterId: 'U005',
    requesterName: 'บีม',
    status: 'PENDING',
    required_approval_level: 3,
    createdAt: '2026-02-15T08:00:00.000Z',
    dueDate: '2026-02-25T17:00:00.000Z',
    priority: 'HIGH'
  },

  // 4. Task ตรวจรับเล่มสำเนาควบคุม SOP-QC-01 Rev.01 ที่จุดตรวจรับ QC Office (Assignee: บีม / QC)
  {
    id: 'task-receipt-sop-qc-01-rev01',
    type: 'DEPT_CONFIRM_HARDCOPY_RECEIPT',
    taskType: 'DEPT_CONFIRM_HARDCOPY_RECEIPT',
    task_type: 'CONFIRM_RECEIPT',
    category: 'RECEIPT',
    title: 'ตรวจรับเอกสารควบคุมฉบับพิมพ์: ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง (SOP-QC-01) (Copy 01)',
    description: 'กรุณาตรวจสอบเอกสารฉบับพิมพ์จริงที่จุดใช้งาน QC Office (QC) และยืนยันการรับเอกสาร',
    copy_id: 'COPY_SOP-QC-01_REV01_01',
    copyId: 'COPY_SOP-QC-01_REV01_01',
    instanceId: 'COPY_SOP-QC-01_REV01_01',
    doc_id: 'DOC-QC-SOP-01-R01',
    darId: 'DAR-2026-002',
    doc_code: 'SOP-QC-01',
    docCode: 'SOP-QC-01',
    docTitle: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    docName: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    doc_version: '01',
    copy_no: '01',
    location: 'QC Office',
    location_name: 'QC Office',
    target_department: 'QC',
    targetDepartment: 'QC',
    recipientDepartment: 'QC',
    recipient_department: 'QC',
    destinationDept: 'QC',
    destination_dept: 'QC',
    department: 'QC',
    departmentName: 'ฝ่ายประกันและควบคุมคุณภาพ',
    dept_code: 'QC',
    currentHandlerDepartment: 'QC',
    isDepartmentPool: true,
    isSharedTask: true,
    shared_pool: true,
    is_shared_task: true,
    assignee_id: 'U005',
    assigneeId: 'U005',
    assignee_name: 'บีม',
    assigneeName: 'บีม',
    assignee_dept: 'QC',
    assignedToDept: 'QC',
    assignedToRole: 'DEPARTMENT_CONTROLLER',
    origin: 'INTERNAL',
    status: 'PENDING',
    createdAt: '2026-02-01T08:00:00.000Z',
    dueDate: '2026-02-10T17:00:00.000Z',
    priority: 'HIGH'
  }
];

export const defaultSeedCopies = [
  // รายการสำเนาประจำจุด QC Office สถานะพร้อมทำงาน (ISSUED_ACTIVE)
  {
    id: 'COPY_SOP-QC-01_REV01_01',
    docId: 'DOC-QC-SOP-01-R01',
    doc_id: 'DOC-QC-SOP-01-R01',
    document_code: 'SOP-QC-01',
    doc_code: 'SOP-QC-01',
    docCode: 'SOP-QC-01',
    document_title: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    docTitle: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    docName: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    title: 'SOP-QC-01',
    name: 'ระเบียบปฏิบัติการควบคุมคุณภาพและการสุ่มตัวอย่าง',
    rev: '01',
    revision: '01',
    doc_version: '01',
    copy_no: '01',
    copy_number: '01',
    copyNo: '01',
    ccNumber: '01',
    location: 'QC Office',
    locationName: 'QC Office',
    location_name: 'QC Office',
    station_name: 'QC Office',
    target_department: 'QC',
    targetDepartment: 'QC',
    department: 'QC',
    dept: 'QC',
    recipientDepartment: 'QC',
    status: 'ISSUED_ACTIVE',
    is_active_in_field: true,
    holder: 'บีม (QC Supervisor)',
    darId: 'DAR-2026-002',
    issueDate: '2026-02-01',
    dispatched_at: '2026-02-01T08:00:00.000Z',
    receipt_confirmed_at: '2026-02-02T09:30:00.000Z'
  }
];
